import type { FabricDef } from '@fitroom/shared';
import { t } from './lib.js';

/**
 * Telas del catálogo. Parámetros físicos tomados de fichas técnicas típicas del sector
 * (gramaje real en g/m², elasticidad 0..1, rigidez a flexión 0..1, hilos o columnas por cm).
 */
export const FABRICS: readonly FabricDef[] = [
  {
    id: 'cotton-jersey-160',
    name: t('Jersey de algodón peinado 160 g', 'Combed cotton jersey, 160 gsm'),
    family: 'cotton-jersey',
    weightGsm: 160,
    stretch: 0.45,
    stiffness: 0.12,
    roughness: 0.86,
    sheen: 0.08,
    threadsPerCm: 14,
    tileCm: 6,
    thicknessMm: 0.55,
  },
  {
    id: 'cotton-jersey-200',
    name: t('Jersey de algodón pesado 200 g', 'Heavyweight cotton jersey, 200 gsm'),
    family: 'cotton-jersey',
    weightGsm: 200,
    stretch: 0.4,
    stiffness: 0.2,
    roughness: 0.88,
    sheen: 0.07,
    threadsPerCm: 13,
    tileCm: 6,
    thicknessMm: 0.7,
  },
  {
    id: 'cotton-rib-220',
    name: t('Canalé de algodón 1×1', 'Cotton 1×1 rib'),
    family: 'cotton-jersey',
    weightGsm: 220,
    stretch: 0.75,
    stiffness: 0.15,
    roughness: 0.9,
    sheen: 0.06,
    threadsPerCm: 16,
    tileCm: 5,
    thicknessMm: 0.9,
  },
  {
    id: 'cotton-pique-210',
    name: t('Piqué de algodón', 'Cotton piqué'),
    family: 'cotton-jersey',
    weightGsm: 210,
    stretch: 0.28,
    stiffness: 0.3,
    roughness: 0.92,
    sheen: 0.05,
    threadsPerCm: 10,
    tileCm: 5,
    thicknessMm: 0.95,
  },
  {
    id: 'poplin-cotton-110',
    name: t('Popelín de algodón', 'Cotton poplin'),
    family: 'cotton-poplin',
    weightGsm: 110,
    stretch: 0.06,
    stiffness: 0.3,
    roughness: 0.62,
    sheen: 0.16,
    threadsPerCm: 38,
    tileCm: 3.5,
    thicknessMm: 0.22,
  },
  {
    id: 'oxford-cotton-135',
    name: t('Oxford de algodón', 'Cotton Oxford cloth'),
    family: 'cotton-poplin',
    weightGsm: 135,
    stretch: 0.06,
    stiffness: 0.42,
    roughness: 0.78,
    sheen: 0.1,
    threadsPerCm: 30,
    tileCm: 4,
    thicknessMm: 0.35,
  },
  {
    id: 'denim-12oz',
    name: t('Denim crudo 12 oz', 'Raw denim, 12 oz'),
    family: 'denim',
    weightGsm: 400,
    stretch: 0.04,
    stiffness: 0.72,
    roughness: 0.9,
    sheen: 0.03,
    threadsPerCm: 24,
    tileCm: 8,
    thicknessMm: 0.9,
  },
  {
    id: 'denim-stretch-9oz',
    name: t('Denim elástico 9 oz', 'Stretch denim, 9 oz'),
    family: 'denim',
    weightGsm: 300,
    stretch: 0.25,
    stiffness: 0.5,
    roughness: 0.86,
    sheen: 0.03,
    threadsPerCm: 26,
    tileCm: 8,
    thicknessMm: 0.75,
  },
  {
    id: 'linen-washed-170',
    name: t('Lino lavado a la piedra', 'Stone-washed linen'),
    family: 'linen',
    weightGsm: 170,
    stretch: 0.03,
    stiffness: 0.4,
    roughness: 0.95,
    sheen: 0.1,
    threadsPerCm: 18,
    tileCm: 6,
    thicknessMm: 0.45,
  },
  {
    id: 'linen-heavy-230',
    name: t('Lino de gramaje medio', 'Mid-weight linen'),
    family: 'linen',
    weightGsm: 230,
    stretch: 0.02,
    stiffness: 0.55,
    roughness: 0.96,
    sheen: 0.08,
    threadsPerCm: 16,
    tileCm: 7,
    thicknessMm: 0.6,
  },
  {
    id: 'wool-knit-chunky',
    name: t('Punto de lana grueso', 'Chunky wool knit'),
    family: 'wool-knit',
    weightGsm: 420,
    stretch: 0.35,
    stiffness: 0.35,
    roughness: 0.98,
    sheen: 0.05,
    threadsPerCm: 5,
    tileCm: 12,
    thicknessMm: 5.5,
  },
  {
    id: 'wool-rib-300',
    name: t('Canalé de lana', 'Wool rib'),
    family: 'wool-knit',
    weightGsm: 300,
    stretch: 0.7,
    stiffness: 0.25,
    roughness: 0.96,
    sheen: 0.05,
    threadsPerCm: 7,
    tileCm: 8,
    thicknessMm: 3.2,
  },
  {
    id: 'merino-fine-gg12',
    name: t('Punto fino de merino galga 12', 'Fine merino knit, 12-gauge'),
    family: 'merino',
    weightGsm: 210,
    stretch: 0.5,
    stiffness: 0.12,
    roughness: 0.8,
    sheen: 0.22,
    threadsPerCm: 12,
    tileCm: 5,
    thicknessMm: 1.4,
  },
  {
    id: 'satin-crepe-back-130',
    name: t('Satén de crepé', 'Crepe-back satin'),
    family: 'satin',
    weightGsm: 130,
    stretch: 0.08,
    stiffness: 0.22,
    roughness: 0.22,
    sheen: 0.85,
    threadsPerCm: 60,
    tileCm: 3,
    thicknessMm: 0.3,
  },
  {
    id: 'silk-crepe-90',
    name: t('Crepé de seda', 'Silk crepe'),
    family: 'silk-crepe',
    weightGsm: 90,
    stretch: 0.1,
    stiffness: 0.1,
    roughness: 0.55,
    sheen: 0.35,
    threadsPerCm: 50,
    tileCm: 3,
    thicknessMm: 0.25,
  },
  {
    id: 'leather-lamb-09',
    name: t('Piel de cordero napa', 'Napa lambskin'),
    family: 'leather',
    weightGsm: 650,
    stretch: 0.08,
    stiffness: 0.6,
    roughness: 0.45,
    sheen: 0.4,
    threadsPerCm: 8,
    tileCm: 14,
    thicknessMm: 1,
  },
  {
    id: 'corduroy-14w',
    name: t('Pana de 14 canalés', '14-wale corduroy'),
    family: 'corduroy',
    weightGsm: 280,
    stretch: 0.05,
    stiffness: 0.55,
    roughness: 0.95,
    sheen: 0.2,
    threadsPerCm: 6,
    tileCm: 6,
    thicknessMm: 1.6,
  },
  {
    id: 'fleece-brushed-320',
    name: t('Muletón perchado', 'Brushed fleece'),
    family: 'fleece',
    weightGsm: 320,
    stretch: 0.3,
    stiffness: 0.25,
    roughness: 0.97,
    sheen: 0.05,
    threadsPerCm: 9,
    tileCm: 8,
    thicknessMm: 3,
  },
  {
    id: 'twill-chino-240',
    name: t('Sarga de algodón para chino', 'Cotton chino twill'),
    family: 'twill',
    weightGsm: 240,
    stretch: 0.08,
    stiffness: 0.5,
    roughness: 0.78,
    sheen: 0.08,
    threadsPerCm: 36,
    tileCm: 5,
    thicknessMm: 0.55,
  },
  {
    id: 'tweed-herringbone-360',
    name: t('Tweed de lana en espiga', 'Wool herringbone tweed'),
    family: 'tweed',
    weightGsm: 360,
    stretch: 0.03,
    stiffness: 0.7,
    roughness: 0.98,
    sheen: 0.04,
    threadsPerCm: 9,
    tileCm: 9,
    thicknessMm: 1.8,
  },
  {
    id: 'tweed-coating-480',
    name: t('Paño de lana para abrigo', 'Wool coating'),
    family: 'tweed',
    weightGsm: 480,
    stretch: 0.02,
    stiffness: 0.65,
    roughness: 0.93,
    sheen: 0.06,
    threadsPerCm: 12,
    tileCm: 9,
    thicknessMm: 3.2,
  },
];
